// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_producer.sql

package dbsqlc

import (
	"context"
	"time"
)

const producerDeleteReaped = `-- name: ProducerDeleteReaped :many
WITH reaped_producers AS (
    SELECT
        queue_name,
        client_id
    FROM /* TEMPLATE: schema */river_producer
    WHERE reaped_at < $1::timestamptz
    ORDER BY
        reaped_at ASC,
        queue_name ASC,
        client_id ASC
    LIMIT $2::bigint
    FOR UPDATE
    SKIP LOCKED
)
DELETE FROM /* TEMPLATE: schema */river_producer
USING reaped_producers
WHERE
    river_producer.queue_name = reaped_producers.queue_name
    AND river_producer.client_id = reaped_producers.client_id
    AND river_producer.reaped_at < $1::timestamptz
RETURNING river_producer.queue_name, river_producer.client_id, river_producer.producer_id, river_producer.generation, river_producer.max_workers, river_producer.created_at, river_producer.updated_at, river_producer.expires_at, river_producer.reaped_at
`

type ProducerDeleteReapedParams struct {
	ReapedAtHorizon time.Time
	Max             int64
}

func (q *Queries) ProducerDeleteReaped(ctx context.Context, db DBTX, arg *ProducerDeleteReapedParams) ([]*RiverProducer, error) {
	rows, err := db.QueryContext(ctx, producerDeleteReaped, arg.ReapedAtHorizon, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverProducer
	for rows.Next() {
		var i RiverProducer
		if err := rows.Scan(
			&i.QueueName,
			&i.ClientID,
			&i.ProducerID,
			&i.Generation,
			&i.MaxWorkers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ReapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const producerFinish = `-- name: ProducerFinish :one
UPDATE /* TEMPLATE: schema */river_producer
SET
    reaped_at = coalesce($1::timestamptz, now())
WHERE
    queue_name = $2::text
    AND client_id = $3::text
    AND generation = $4::bigint
    AND reaped_at IS NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerFinishParams struct {
	Now        *time.Time
	QueueName  string
	ClientID   string
	Generation int64
}

func (q *Queries) ProducerFinish(ctx context.Context, db DBTX, arg *ProducerFinishParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerFinish,
		arg.Now,
		arg.QueueName,
		arg.ClientID,
		arg.Generation,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerGet = `-- name: ProducerGet :one
SELECT queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
FROM /* TEMPLATE: schema */river_producer
WHERE
    queue_name = $1::text
    AND client_id = $2::text
`

type ProducerGetParams struct {
	QueueName string
	ClientID  string
}

func (q *Queries) ProducerGet(ctx context.Context, db DBTX, arg *ProducerGetParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerGet, arg.QueueName, arg.ClientID)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerInsert = `-- name: ProducerInsert :one
INSERT INTO /* TEMPLATE: schema */river_producer (
    queue_name,
    client_id,
    producer_id,
    generation,
    max_workers,
    created_at,
    updated_at,
    expires_at,
    reaped_at
) VALUES (
    $1::text,
    $2::text,
    $3::bigint,
    1,
    $4::bigint,
    coalesce($5::timestamptz, now()),
    coalesce($5::timestamptz, now()),
    coalesce($5::timestamptz, now()) + make_interval(secs => $6),
    NULL
)
ON CONFLICT (queue_name, client_id) DO UPDATE
SET
    producer_id = EXCLUDED.producer_id,
    generation = river_producer.generation + 1,
    max_workers = EXCLUDED.max_workers,
    updated_at = EXCLUDED.updated_at,
    expires_at = EXCLUDED.expires_at,
    reaped_at = NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerInsertParams struct {
	QueueName  string
	ClientID   string
	ProducerID int64
	MaxWorkers int64
	Now        *time.Time
	TTL        float64
}

func (q *Queries) ProducerInsert(ctx context.Context, db DBTX, arg *ProducerInsertParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerInsert,
		arg.QueueName,
		arg.ClientID,
		arg.ProducerID,
		arg.MaxWorkers,
		arg.Now,
		arg.TTL,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerKeepAlive = `-- name: ProducerKeepAlive :one
UPDATE /* TEMPLATE: schema */river_producer
SET
    updated_at = coalesce($1::timestamptz, now()),
    expires_at = coalesce($1::timestamptz, now()) + make_interval(secs => $2)
WHERE
    queue_name = $3::text
    AND client_id = $4::text
    AND generation = $5::bigint
    AND reaped_at IS NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerKeepAliveParams struct {
	Now        *time.Time
	TTL        float64
	QueueName  string
	ClientID   string
	Generation int64
}

func (q *Queries) ProducerKeepAlive(ctx context.Context, db DBTX, arg *ProducerKeepAliveParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerKeepAlive,
		arg.Now,
		arg.TTL,
		arg.QueueName,
		arg.ClientID,
		arg.Generation,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerReapExpired = `-- name: ProducerReapExpired :many
WITH expired_producers AS (
    SELECT
        queue_name,
        client_id
    FROM /* TEMPLATE: schema */river_producer
    WHERE
        expires_at < coalesce($1::timestamptz, now())
        AND reaped_at IS NULL
    ORDER BY
        expires_at ASC,
        queue_name ASC,
        client_id ASC
    LIMIT $2::bigint
    FOR UPDATE
    SKIP LOCKED
)
UPDATE /* TEMPLATE: schema */river_producer
SET
    reaped_at = coalesce($1::timestamptz, now())
FROM expired_producers
WHERE
    river_producer.queue_name = expired_producers.queue_name
    AND river_producer.client_id = expired_producers.client_id
    AND river_producer.expires_at < coalesce($1::timestamptz, now())
    AND river_producer.reaped_at IS NULL
RETURNING river_producer.queue_name, river_producer.client_id, river_producer.producer_id, river_producer.generation, river_producer.max_workers, river_producer.created_at, river_producer.updated_at, river_producer.expires_at, river_producer.reaped_at
`

type ProducerReapExpiredParams struct {
	Now *time.Time
	Max int64
}

func (q *Queries) ProducerReapExpired(ctx context.Context, db DBTX, arg *ProducerReapExpiredParams) ([]*RiverProducer, error) {
	rows, err := db.QueryContext(ctx, producerReapExpired, arg.Now, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverProducer
	for rows.Next() {
		var i RiverProducer
		if err := rows.Scan(
			&i.QueueName,
			&i.ClientID,
			&i.ProducerID,
			&i.Generation,
			&i.MaxWorkers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ReapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
