// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_queue_drain.sql

package dbsqlc

import (
	"context"
	"time"
)

const queueDrainComplete = `-- name: QueueDrainComplete :execrows
UPDATE /* TEMPLATE: schema */river_queue_drain
SET
    state = 'drained',
    drained_at = coalesce(cast(?1 AS text), datetime('now', 'subsec')),
    updated_at = coalesce(cast(?1 AS text), datetime('now', 'subsec'))
WHERE cast(queue AS text) = cast(?2 AS text)
    AND state = 'draining'
    AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */river_job
        WHERE river_job.queue = river_queue_drain.queue
            AND river_job.state = 'running'
    )
`

type QueueDrainCompleteParams struct {
	Now   *string
	Queue string
}

func (q *Queries) QueueDrainComplete(ctx context.Context, db DBTX, arg *QueueDrainCompleteParams) (int64, error) {
	result, err := db.ExecContext(ctx, queueDrainComplete, arg.Now, arg.Queue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queueDrainDeleteResumed = `-- name: QueueDrainDeleteResumed :execrows
DELETE FROM /* TEMPLATE: schema */river_queue_drain
WHERE state = 'resumed'
    AND updated_at < cast(?1 AS text)
`

type QueueDrainDeleteResumedParams struct {
	UpdatedAtHorizon string
}

func (q *Queries) QueueDrainDeleteResumed(ctx context.Context, db DBTX, arg *QueueDrainDeleteResumedParams) (int64, error) {
	result, err := db.ExecContext(ctx, queueDrainDeleteResumed, arg.UpdatedAtHorizon)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queueDrainGetActive = `-- name: QueueDrainGetActive :one
SELECT
    d.queue,
    d.key,
    d.state,
    d.created_at,
    d.drained_at,
    d.resumed_at,
    d.updated_at,
    (
        SELECT count(*)
        FROM /* TEMPLATE: schema */river_job
        WHERE river_job.queue = d.queue
            AND river_job.state = 'running'
    ) AS running_count
FROM /* TEMPLATE: schema */river_queue_drain d
WHERE cast(d.queue AS text) = cast(?1 AS text)
    AND d.state IN ('draining', 'drained')
`

type QueueDrainGetActiveRow struct {
	Queue        string
	Key          string
	State        string
	CreatedAt    time.Time
	DrainedAt    *time.Time
	ResumedAt    *time.Time
	UpdatedAt    time.Time
	RunningCount int64
}

func (q *Queries) QueueDrainGetActive(ctx context.Context, db DBTX, queue string) (*QueueDrainGetActiveRow, error) {
	row := db.QueryRowContext(ctx, queueDrainGetActive, queue)
	var i QueueDrainGetActiveRow
	err := row.Scan(
		&i.Queue,
		&i.Key,
		&i.State,
		&i.CreatedAt,
		&i.DrainedAt,
		&i.ResumedAt,
		&i.UpdatedAt,
		&i.RunningCount,
	)
	return &i, err
}

const queueDrainGetByKey = `-- name: QueueDrainGetByKey :one
SELECT
    d.queue,
    d.key,
    d.state,
    d.created_at,
    d.drained_at,
    d.resumed_at,
    d.updated_at,
    (
        SELECT count(*)
        FROM /* TEMPLATE: schema */river_job
        WHERE river_job.queue = d.queue
            AND river_job.state = 'running'
    ) AS running_count
FROM /* TEMPLATE: schema */river_queue_drain d
WHERE cast(d.queue AS text) = cast(?1 AS text)
    AND cast(d.key AS text) = cast(?2 AS text)
`

type QueueDrainGetByKeyParams struct {
	Key   string
	Queue string
}

type QueueDrainGetByKeyRow struct {
	Queue        string
	Key          string
	State        string
	CreatedAt    time.Time
	DrainedAt    *time.Time
	ResumedAt    *time.Time
	UpdatedAt    time.Time
	RunningCount int64
}

func (q *Queries) QueueDrainGetByKey(ctx context.Context, db DBTX, arg *QueueDrainGetByKeyParams) (*QueueDrainGetByKeyRow, error) {
	row := db.QueryRowContext(ctx, queueDrainGetByKey, arg.Queue, arg.Key)
	var i QueueDrainGetByKeyRow
	err := row.Scan(
		&i.Queue,
		&i.Key,
		&i.State,
		&i.CreatedAt,
		&i.DrainedAt,
		&i.ResumedAt,
		&i.UpdatedAt,
		&i.RunningCount,
	)
	return &i, err
}

const queueDrainInsert = `-- name: QueueDrainInsert :one
INSERT INTO /* TEMPLATE: schema */river_queue_drain (
    queue,
    key,
    state,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    'draining',
    coalesce(cast(?3 AS text), datetime('now', 'subsec')),
    coalesce(cast(?3 AS text), datetime('now', 'subsec'))
) ON CONFLICT DO NOTHING
RETURNING queue, key, state, created_at, drained_at, resumed_at, updated_at
`

type QueueDrainInsertParams struct {
	Key   string
	Now   *string
	Queue string
}

func (q *Queries) QueueDrainInsert(ctx context.Context, db DBTX, arg *QueueDrainInsertParams) (*RiverQueueDrain, error) {
	row := db.QueryRowContext(ctx, queueDrainInsert, arg.Queue, arg.Key, arg.Now)
	var i RiverQueueDrain
	err := row.Scan(
		&i.Queue,
		&i.Key,
		&i.State,
		&i.CreatedAt,
		&i.DrainedAt,
		&i.ResumedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const queueDrainResume = `-- name: QueueDrainResume :execrows
UPDATE /* TEMPLATE: schema */river_queue_drain
SET
    state = 'resumed',
    resumed_at = coalesce(cast(?1 AS text), datetime('now', 'subsec')),
    updated_at = coalesce(cast(?1 AS text), datetime('now', 'subsec'))
WHERE cast(queue AS text) = cast(?2 AS text)
    AND state = 'drained'
`

type QueueDrainResumeParams struct {
	Now   *string
	Queue string
}

func (q *Queries) QueueDrainResume(ctx context.Context, db DBTX, arg *QueueDrainResumeParams) (int64, error) {
	result, err := db.ExecContext(ctx, queueDrainResume, arg.Now, arg.Queue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
