// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_producer.sql

package dbsqlc

import (
	"context"
)

const producerDeleteReaped = `-- name: ProducerDeleteReaped :many
DELETE FROM /* TEMPLATE: schema */river_producer
WHERE (queue_name, client_id) IN (
    SELECT
        queue_name,
        client_id
    FROM /* TEMPLATE: schema */river_producer
    WHERE reaped_at < cast(?1 AS text)
    ORDER BY
        reaped_at ASC,
        queue_name ASC,
        client_id ASC
    LIMIT ?2
)
    AND reaped_at < cast(?1 AS text)
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerDeleteReapedParams struct {
	ReapedAtHorizon string
	Max             int64
}

func (q *Queries) ProducerDeleteReaped(ctx context.Context, db DBTX, arg *ProducerDeleteReapedParams) ([]*RiverProducer, error) {
	rows, err := db.QueryContext(ctx, producerDeleteReaped, arg.ReapedAtHorizon, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverProducer
	for rows.Next() {
		var i RiverProducer
		if err := rows.Scan(
			&i.QueueName,
			&i.ClientID,
			&i.ProducerID,
			&i.Generation,
			&i.MaxWorkers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ReapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const producerFinish = `-- name: ProducerFinish :one
UPDATE /* TEMPLATE: schema */river_producer
SET
    reaped_at = coalesce(cast(?1 AS text), datetime('now', 'subsec'))
WHERE
    queue_name = ?2
    AND client_id = ?3
    AND generation = ?4
    AND reaped_at IS NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerFinishParams struct {
	Now        *string
	QueueName  string
	ClientID   string
	Generation int64
}

func (q *Queries) ProducerFinish(ctx context.Context, db DBTX, arg *ProducerFinishParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerFinish,
		arg.Now,
		arg.QueueName,
		arg.ClientID,
		arg.Generation,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerGet = `-- name: ProducerGet :one
SELECT queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
FROM /* TEMPLATE: schema */river_producer
WHERE
    queue_name = ?1
    AND client_id = ?2
`

type ProducerGetParams struct {
	QueueName string
	ClientID  string
}

func (q *Queries) ProducerGet(ctx context.Context, db DBTX, arg *ProducerGetParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerGet, arg.QueueName, arg.ClientID)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerInsert = `-- name: ProducerInsert :one
INSERT INTO /* TEMPLATE: schema */river_producer (
    queue_name,
    client_id,
    producer_id,
    generation,
    max_workers,
    created_at,
    updated_at,
    expires_at,
    reaped_at
) VALUES (
    ?1,
    ?2,
    ?3,
    1,
    ?4,
    coalesce(cast(?5 AS text), datetime('now', 'subsec')),
    coalesce(cast(?5 AS text), datetime('now', 'subsec')),
    datetime(coalesce(cast(?5 AS text), datetime('now', 'subsec')), 'subsec', cast(?6 AS text)),
    NULL
)
ON CONFLICT (queue_name, client_id) DO UPDATE
SET
    producer_id = EXCLUDED.producer_id,
    generation = river_producer.generation + 1,
    max_workers = EXCLUDED.max_workers,
    updated_at = EXCLUDED.updated_at,
    expires_at = EXCLUDED.expires_at,
    reaped_at = NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerInsertParams struct {
	QueueName  string
	ClientID   string
	ProducerID int64
	MaxWorkers int64
	Now        *string
	TTL        string
}

func (q *Queries) ProducerInsert(ctx context.Context, db DBTX, arg *ProducerInsertParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerInsert,
		arg.QueueName,
		arg.ClientID,
		arg.ProducerID,
		arg.MaxWorkers,
		arg.Now,
		arg.TTL,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerKeepAlive = `-- name: ProducerKeepAlive :one
UPDATE /* TEMPLATE: schema */river_producer
SET
    updated_at = coalesce(cast(?1 AS text), datetime('now', 'subsec')),
    expires_at = datetime(coalesce(cast(?1 AS text), datetime('now', 'subsec')), 'subsec', cast(?2 AS text))
WHERE
    queue_name = ?3
    AND client_id = ?4
    AND generation = ?5
    AND reaped_at IS NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerKeepAliveParams struct {
	Now        *string
	TTL        string
	QueueName  string
	ClientID   string
	Generation int64
}

func (q *Queries) ProducerKeepAlive(ctx context.Context, db DBTX, arg *ProducerKeepAliveParams) (*RiverProducer, error) {
	row := db.QueryRowContext(ctx, producerKeepAlive,
		arg.Now,
		arg.TTL,
		arg.QueueName,
		arg.ClientID,
		arg.Generation,
	)
	var i RiverProducer
	err := row.Scan(
		&i.QueueName,
		&i.ClientID,
		&i.ProducerID,
		&i.Generation,
		&i.MaxWorkers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ReapedAt,
	)
	return &i, err
}

const producerReapExpired = `-- name: ProducerReapExpired :many
UPDATE /* TEMPLATE: schema */river_producer
SET
    reaped_at = coalesce(cast(?1 AS text), datetime('now', 'subsec'))
WHERE (queue_name, client_id) IN (
    SELECT
        queue_name,
        client_id
    FROM /* TEMPLATE: schema */river_producer
    WHERE
        expires_at < coalesce(cast(?1 AS text), datetime('now', 'subsec'))
        AND reaped_at IS NULL
    ORDER BY
        expires_at ASC,
        queue_name ASC,
        client_id ASC
    LIMIT ?2
)
    AND expires_at < coalesce(cast(?1 AS text), datetime('now', 'subsec'))
    AND reaped_at IS NULL
RETURNING queue_name, client_id, producer_id, generation, max_workers, created_at, updated_at, expires_at, reaped_at
`

type ProducerReapExpiredParams struct {
	Now *string
	Max int64
}

func (q *Queries) ProducerReapExpired(ctx context.Context, db DBTX, arg *ProducerReapExpiredParams) ([]*RiverProducer, error) {
	rows, err := db.QueryContext(ctx, producerReapExpired, arg.Now, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverProducer
	for rows.Next() {
		var i RiverProducer
		if err := rows.Scan(
			&i.QueueName,
			&i.ClientID,
			&i.ProducerID,
			&i.Generation,
			&i.MaxWorkers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ReapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
